### ISSUE TITLE
LICENSE 

### ISSUE THREAD

**Issue by quocanh010** [Amirhossein-Nayebi/Nordic-Vehicle-Dataset#2]
Thanks for the work. Could you post a License for the use of this data?

**Comment by amrdev-pixel** [comment]
Thank you for your interest! I have updated the README file with the license information for the dataset. You can now find the details regarding the license and permitted usage in the ReadMe.md file. If you have any further questions or need additional information, please feel free to ask. Happy exploring!

**Comment by MHLeventoglu** [comment]
Thanks for the work. I was wondering how can I access to this dataset?
